### ISSUE TITLE
Crash IndexError (maybe is the Issue #30 happening again)

### ISSUE THREAD

**Issue by richarddribeiro** [vinifmor/fpakman#38]
Hi,
Thank you for your fantastic work. I am still beginning to test Snaps and Flatpacks, but I am liking the whole concept. However, after the latest Manjaro update (https://forum.manjaro.org/t/stable-update-2019-10-10-gnome-3-34-1-plasma-5-16-5-kde-apps-framework-pamac-9-0-mesa-19-2-1/106563/229) I started to having problems with Bauh. The issue seems to be the same as the one related here: Crash IndexError (https://github.com/vinifmor/fpakman/issues/30)

```
$ bauh
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bauh/view/qt/thread.py", line 120, in run
    res = self.manager.read_installed(pkg_types=self.pkg_types)
  File "/usr/lib/python3.7/site-packages/bauh/view/core/controller.py", line 168, in read_installed
    man_res = man.read_installed(disk_loader=disk_loader, pkg_types=None, internet_available=net_check['available'])
  File "/usr/lib/python3.7/site-packages/bauh/gems/snap/controller.py", line 86, in read_installed
    installed = [self.map_json(app_json, installed=True, disk_loader=disk_loader, internet=internet_available) for app_json in snap.read_installed()]
  File "/usr/lib/python3.7/site-packages/bauh/gems/snap/snap.py", line 112, in read_installed
    apps[idx]['type'] = line.split(':')[1].strip()
IndexError: list index out of range
Aborted (core dumped)
```
My specs:
```
System:    Host: gemini Kernel: 5.3.5-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: Xfce 4.14.1 tk: Gtk 3.24.12 
           info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Inspiron 7472 v: N/A serial: <root required> Chassis: type: 10 
           serial: <root required> 
           Mobo: Dell model: 082HPJ v: A03 serial: <root required> UEFI: Dell v: 1.2.1 date: 05/31/2019 
Battery:   ID-1: BAT0 charge: 39.9 Wh condition: 39.9/42.0 Wh (95%) volts: 12.7/11.4 model: SMP DELL Y3F7Y6B type: Li-ion 
           serial: 2080 status: Full 
CPU:       Topology: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP arch: Kaby Lake rev: A L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 32012 
           Speed: 612 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 612 2: 609 3: 644 4: 705 5: 631 6: 665 7: 622 8: 653 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:5917 
           Device-2: NVIDIA GP108M [GeForce MX150] driver: N/A bus ID: 01:00.0 chip ID: 10de:1d10 
           Display: x11 server: X.Org 1.20.5 driver: intel resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) v: 4.5 Mesa 19.2.1 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           chip ID: 8086:9d71 
           Sound Server: ALSA v: k5.3.5-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell driver: r8168 v: 8.047.04-NAPI 
           port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: down mac: b8:85:84:fe:82:85 
           Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter vendor: Dell driver: ath10k_pci v: kernel 
           port: d000 bus ID: 03:00.0 chip ID: 168c:003e 
           IF: wlp3s0 state: up mac: 92:a6:8e:0a:bf:0c 
           Device-3: Qualcomm Atheros type: USB driver: btusb bus ID: 1-7:4 chip ID: 0cf3:e007 
Drives:    Local Storage: total: 1.03 TiB used: 468.34 GiB (44.6%) 
           ID-1: /dev/sda vendor: Western Digital model: WD10SPZX-75Z10T2 size: 931.51 GiB speed: 6.0 Gb/s rotation: 5400 rpm 
           serial: WXA1AA8ECYH9 rev: 1A03 scheme: GPT 
           ID-2: /dev/sdb vendor: A-Data model: SU810NS38 SATA 128 GB size: 119.24 GiB speed: 6.0 Gb/s serial: DI4720004423 
           rev: 1101 scheme: GPT 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 port: f060 bus ID: 00:17.0 
           chip ID: 8086.282a rev: 21 
Partition: ID-1: / size: 898.75 GiB used: 431.01 GiB (48.0%) fs: ext4 dev: /dev/sda2 
           ID-2: swap-1 size: 17.12 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 45.0 C mobo: 35.0 C sodimm: 39.0 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 304 Uptime: 1h 06m Memory: 15.54 GiB used: 4.54 GiB (29.2%) Init: systemd v: 242 Compilers: gcc: 9.2.0 
           Shell: bash v: 5.0.11 running in: xfce4-terminal inxi: 3.0.36 
```
```
$ snap list
Name               Version                     Rev   Tracking  Publisher   Notes
bitwarden          1.16.6                      21    stable    bitwarden✓  -
core               16-2.42                     7917  stable    canonical✓  core
core18             20191001                    1192  stable    canonical✓  base
gnome-3-28-1804    3.28.0-10-gaa70833.aa70833  71    stable    canonical✓  -
gtk-common-themes  0.1-25-gcc83164             1353  stable    canonical✓  -
musixmatch         3.6.1                       18    stable    musixmatch  -
olivia             1.0                         36    stable    keshavnrj   -
projectlibre       1.9.1                       3     stable    jibel       -
qt551              5.5                         17    stable    keshavnrj   -
snap-store         20190829.daf5512            188   stable    canonical✓  -
snapd              2.42                        4992  stable    canonical✓  snapd
spotify            1.1.10.546.ge08ef575-19     36    stable    spotify✓    
```
Can you shed some light on the problem, please?

Thanks

**Comment by alexeiroz** [comment]
I have the same problem on manjaro

```
[ ~]$ bauh 
qt5ct: using qt5ct plugin
qt5ct: palette support is disabled
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 18239, resource id: 11754426, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 18525, resource id: 11762170, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 381, in run
    requirements = self.manager.get_upgrade_requirements(models, root_password, self)
  File "/usr/lib/python3.8/site-packages/bauh/view/core/controller.py", line 472, in get_upgrade_requirements
    man_reqs = man.get_upgrade_requirements(pkgs, root_password, watcher)
  File "/usr/lib/python3.8/site-packages/bauh/gems/flatpak/controller.py", line 517, in get_upgrade_requirements
    sizes = flatpak.map_update_download_size([str(p.id) for p in apps_by_install[0]], apps_by_install[1], flatpak_version)
  File "/usr/lib/python3.8/site-packages/bauh/gems/flatpak/flatpak.py", line 412, in map_update_download_size
    res[related_id[0].strip()] = size_to_byte(float(size[0]), size[1])
IndexError: list index out of range
Aborted (core dumped)
```

**Comment by vinifmor** [comment]
Please, open this issue in bauh's page. This repository is no longer maintained,
