### ISSUE TITLE
Crashes : core dumped

### ISSUE THREAD

**Issue by nam1962** [vinifmor/fpakman#6]
Hi, thank you for this interesting project.
While it initially worked flawless, it's now crashing, here the details : 
```
~]$ fpakman
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
error: Multiple branches available for org.freedesktop.Platform.VAAPI.Intel, you must specify one of: org.freedesktop.Platform.VAAPI.Intel//1.6, org.freedesktop.Platform.VAAPI.Intel//18.08
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fpakman/view/qt/systray.py", line 26, in run
    apps = self.controller.refresh()
  File "/usr/lib/python3.7/site-packages/fpakman/core/controller.py", line 12, in refresh
    return self.model.read_installed()
  File "/usr/lib/python3.7/site-packages/fpakman/core/model.py", line 44, in read_installed
    installed = flatpak.list_installed()
  File "/usr/lib/python3.7/site-packages/fpakman/core/flatpak.py", line 66, in list_installed
    return [app_str_to_json(line, version) for line in app_lines if line]
  File "/usr/lib/python3.7/site-packages/fpakman/core/flatpak.py", line 66, in <listcomp>
    return [app_str_to_json(line, version) for line in app_lines if line]
  File "/usr/lib/python3.7/site-packages/fpakman/core/flatpak.py", line 35, in app_str_to_json
    info = re.findall('\w+:\s.+', get_app_info(app['id']))
  File "/usr/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
Abandon (core dumped)
```

```
~]$ flatpak list
Name                                            Application ID                                Version             Branch        Installation
Skype                                           com.skype.Client                              8.45.0.41           stable        system
Gradio                                          de.haeckerfelix.gradio                        7.2                 stable        system
UberWriter                                      de.wolfvollprecht.UberWriter                  2.1.5-beta2         stable        system
Freedesktop Platform                            org.freedesktop.Platform                      18.08.32            18.08         system
Intel VAAPI Driver                              org.freedesktop.Platform.VAAPI.Intel                              1.6           system
Intel                                           org.freedesktop.Platform.VAAPI.Intel                              18.08         system
FFmpeg extension                                org.freedesktop.Platform.ffmpeg                                   1.6           system
html5-codecs                                    org.freedesktop.Platform.html5-codecs                             18.08         system
GNOME Application Platform version 3.28         org.gnome.Platform                                                3.28          system
GNOME Application Platform version 3.32         org.gnome.Platform                                                3.32          system
```

```
~]$ inxi -Fxxx
System:    Host: ordinateur Kernel: 5.1.8-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Xfce 4.13.4git-be04da 
           tk: Gtk 3.24.8 info: xfce4-panel wm: xfwm4 dm: LightDM 1.28.0 Distro: Manjaro Linux 
Machine:   Type: Laptop System: ASUSTeK product: K53SD v: 1.0 serial: <root required> 
           Mobo: ASUSTeK model: K53SD v: 1.0 serial: <root required> UEFI: American Megatrends v: K53SD.208 date: 08/10/2012 
Battery:   ID-1: BAT0 charge: 2.5 Wh condition: 2.6/57.2 Wh (5%) volts: 12.5/11.1 model: ASUSTek K53--52 type: Li-ion 
           serial:   status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i3-2350M bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 18367 
           Speed: 807 MHz min/max: 800/2300 MHz Core speeds (MHz): 1: 1327 2: 1226 3: 1604 4: 1866 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: ASUSTeK driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0116 
           Device-2: NVIDIA GF119M [GeForce 610M] vendor: ASUSTeK driver: nouveau v: kernel bus ID: 01:00.0 chip ID: 10de:1058 
           Display: x11 server: X.Org 1.20.5 driver: intel,nouveau unloaded: modesetting alternate: fbdev,nv,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 19.0.6 compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 chip ID: 8086:1c20 
           Sound Server: ALSA v: k5.1.8-1-MANJARO 
Network:   Device-1: Intel Centrino Wireless-N 100 driver: iwlwifi v: kernel port: d000 bus ID: 03:00.0 chip ID: 8086:08ae 
           IF: wlp3s0 state: up mac: 78:92:9c:95:7a:b2 
           Device-2: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet vendor: ASUSTeK driver: atl1c v: 1.0.1.1-NAPI port: 9000 
           bus ID: 05:00.0 chip ID: 1969:1083 
           IF: enp5s0 state: down mac: 10:bf:48:0f:dd:cf 
Drives:    Local Storage: total: 931.51 GiB used: 381.50 GiB (41.0%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000LM024 HN-M101MBB size: 931.51 GiB speed: 3.0 Gb/s rotation: 5400 rpm 
           serial: S2TTJ9CC400760 rev: 0001 scheme: MBR 
Partition: ID-1: / size: 94.66 GiB used: 20.47 GiB (21.6%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 820.49 GiB used: 361.03 GiB (44.0%) fs: ext4 dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 51.0 C mobo: N/A gpu: nouveau temp: 51 C 
           Fan Speeds (RPM): cpu: 2000 
Info:      Processes: 223 Uptime: 1d 6h 00m Memory: 11.51 GiB used: 4.56 GiB (39.6%) Init: systemd v: 242 Compilers: 
           gcc: 8.3.0 Shell: bash v: 5.0.7 running in: xfce4-terminal inxi: 3.0.34 
```

**Comment by vinifmor** [comment]
Hi, 
Thank you for your feedback. I will have a look at this issue and publish the fix into the next release.
If you want to use the previous version, install it via with pip with the following commands:
``
sudo pip install fpakman==0.1
``

**Comment by vinifmor** [comment]
This issue is related to your **runtime** apps. For now, if you want a quick fix, update them via command line with: 
``
flatpak update -y
``

**Comment by nam1962** [comment]
Hi ! Thank you for caring
It's indeed related to my install, but not to its freshness (I update several time.. a day ! ;) )
```
~]$  flatpak update -y
Looking for updates…
Nothing to do.
```
I suspect Gradio on our problem. The question being : how does it break !

**Comment by vinifmor** [comment]
I've already fixed it and published to the **staging** branch. If you want to use it via **AUR**, install **fpakman-staging**.
